# Site settings
title: toolbox
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://containers.github.io/toolbox/" # the base hostname & protocol for your site

permalink: /:title/

# Build settings
markdown: kramdown
