FROM docker.io/library/archlinux:base-devel

LABEL com.github.containers.toolbox="true" \
      name="arch-toolbox" \
      version="base-devel" \
      usage="This image is meant to be used with the toolbox command" \
      summary="Base image for creating Arch Linux Toolbx containers" \
      maintainer="Morten Linderud <foxboron@archlinux.org>"

# Install extra packages
COPY extra-packages /
RUN pacman -Syu --needed --noconfirm - < extra-packages
RUN rm /extra-packages

# Enable man pages, enable progress bars
RUN sed -i -e 's/NoProgressBar/#NoProgressBar/' -e 's/NoExtract/#NoExtract/' /etc/pacman.conf

# Force reinstall of packages which have man pages (shouldn't redownload any that were just upgraded)
RUN mkdir -p /usr/share/man && pacman -Qo /usr/share/man | awk '{print $5}' | xargs pacman -S --noconfirm man-db

# Clean up cache
RUN yes | pacman -Scc

# Enable sudo permission for wheel users
RUN echo "%wheel ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/toolbox
