---
- hosts: all
  tasks:
    - name: Install requirements
      become: yes
      package:
        use: dnf
        name:
          - golang
          - golang-github-cpuguy83-md2man
          - ninja-build
          - meson
          - flatpak-session-helper
          - systemd
          - bats
          - bash-completion
          - udisks2
          - podman

    - name: Install bats-support library
      git:
        repo: https://github.com/bats-core/bats-support
        dest: '{{ zuul.project.src_dir }}/test/system/libs/bats-support'
        depth: 1

    - name: Install bats-assert library
      git:
        repo: https://github.com/bats-core/bats-assert
        dest: '{{ zuul.project.src_dir }}/test/system/libs/bats-assert'
        depth: 1

    - name: Setup environment
      become: yes
      command:
        cmd: systemd-tmpfiles --create
        creates: /run/media

    - name: Check versions of crucial packages
      command: rpm -q golang podman crun conmon fuse-overlayfs flatpak-session-helper

    - name: Pull registry.fedoraproject.org/f31/fedora-toolbox:31
      command: podman pull registry.fedoraproject.org/f31/fedora-toolbox:31
      register: _podman
      until: _podman.rc == 0
      retries: 5
      delay: 10

    - name: Pull registry.fedoraproject.org/f29/fedora-toolbox:29
      command: podman pull registry.fedoraproject.org/f29/fedora-toolbox:29
      register: _podman
      until: _podman.rc == 0
      retries: 5
      delay: 10
