---
- hosts: ci-node-31
  tasks:
    - name: Build toolbox
      command: meson builddir
      args:
        chdir: '{{ zuul.project.src_dir }}'

    - name: Install toolbox
      become: yes
      command: ninja -C builddir install
      args:
        chdir: '{{ zuul.project.src_dir }}'

    - name: Run system tests
      command: bats ./test/system
      environment:
        PODMAN: '/usr/bin/podman'
        TOOLBOX: './toolbox'
      args:
        chdir: '{{ zuul.project.src_dir }}'
