---
- hosts: all
  tasks:
    - name: Install requirements
      become: yes
      package:
        name:
          - golang-github-cpuguy83-go-md2man
          - ninja-build
          - meson
          - flatpak-session-helper
          - systemd
          - bats
          - bash-completion
          - udisks2
          - podman

    - name: Setup environment (create missing /run/media)
      command: sudo systemd-tmpfiles --create

    - name: Check versions of crucial packages
      command: rpm -q podman runc conmon fuse-overlayfs flatpak-session-helper
