#!/bin/sh
#
# Copyright © 2020 – 2021 Red Hat Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


if [ "$#" -ne 4 ]; then
    echo "go-build-wrapper: wrong arguments" >&2
    echo "Usage: go-build-wrapper [SOURCE DIR] [OUTPUT DIR] [VERSION] [C COMPILER]" >&2
    exit 1
fi

if ! cd "$1"; then
    echo "go-build-wrapper: failed to enter source directory $1"
    exit 1
fi

if ! libc_dir=$("$4" --print-file-name=libc.so); then
    echo "go-build-wrapper: failed to read the path to libc.so" >&2
    exit 1
fi

if ! libc_dir_canonical=$(readlink --canonicalize "$libc_dir"); then
    echo "go-build-wrapper: failed to canonicalize the path to libc.so" >&2
    exit 1
fi

if ! libc_dir_canonical_dirname=$(dirname "$libc_dir_canonical"); then
    echo "go-build-wrapper: failed to read the dirname of the canonicalized path to libc.so" >&2
    exit 1
fi

go build -trimpath -ldflags "-extldflags '-Wl,-rpath,/run/host$libc_dir_canonical_dirname' -linkmode external -X github.com/containers/toolbox/pkg/version.currentVersion=$3" -o "$2/toolbox"

if ! interpreter=$(patchelf --print-interpreter "$2/toolbox"); then
    echo "go-build-wrapper: failed to read PT_INTERP from $2/toolbox" >&2
    exit 1
fi

if ! interpreter_canonical=$(readlink --canonicalize "$interpreter"); then
    echo "go-build-wrapper: failed to canonicalize PT_INTERP" >&2
    exit 1
fi

if ! interpreter_basename=$(basename "$interpreter"); then
    echo "go-build-wrapper: failed to read the basename of PT_INTERP" >&2
    exit 1
fi

if ! interpreter_canonical_dirname=$(dirname "$interpreter_canonical"); then
    echo "go-build-wrapper: failed to read the dirname of the canonicalized PT_INTERP" >&2
    exit 1
fi

interpreter="/run/host$interpreter_canonical_dirname/$interpreter_basename"

if ! patchelf --set-interpreter "$interpreter" "$2/toolbox"; then
    echo "go-build-wrapper: failed to change PT_INTERP of $2/toolbox to $interpreter" >&2
    exit 1
fi

exit "$?"
