#
# Copyright © 2026 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

- name: Synchronize glibc to repo version for gcc/glibc-devel compatibility
  become: yes
  command: >-
    rpm-ostree override replace --experimental --from repo=updates
      glibc
      glibc-common
      glibc-minimal-langpack
      glibc-gconv-extra
  ignore_errors: yes

- name: Synchronize shadow-utils to repo version for shadow-utils-subid-devel compatibility
  become: yes
  command: rpm-ostree override replace --experimental --from repo=updates shadow-utils
  ignore_errors: yes

- name: Apply base package overrides
  become: yes
  command: rpm-ostree apply-live --allow-replacement
  ignore_errors: yes

- name: Install RPM packages
  become: yes
  command: >-
    rpm-ostree install --allow-inactive --apply-live --assumeyes --idempotent
      ShellCheck
      bats
      codespell
      gcc
      golang
      golang-github-cpuguy83-md2man
      httpd-tools
      meson
      ninja-build
      shadow-utils-subid-devel
      udisks2

- include_tasks: dependencies-common.yaml
