---
- hosts: all
  tasks:
    - name: Run system tests
      command: bats --timing ./test/system
      environment:
        PODMAN: '/usr/bin/podman'
        TOOLBOX: '/usr/local/bin/toolbox'
      args:
        chdir: '{{ zuul.project.src_dir }}'
