name: "Images: Build and push Debian toolbx images"

on:
  push:
    branches:
      - main
    paths:
      - images/debian/**
      - .github/workflows/debian-images.yaml
  schedule:
    - cron: '0 0 * * MON'

# Prevent multiple workflow runs from racing
concurrency: ${{ github.workflow }}

env:
  latest_release: '12'

jobs:
  build-and-push-images:
    strategy:
      matrix:
        release: ['10', '11', '12', 'testing', 'unstable']

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: 'toolbx+github'
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: Build and push Debian ${{ matrix.release }} toolbox image
        uses: docker/build-push-action@v3
        with:
          context: images/debian/${{ matrix.release }}
          file: images/debian/${{ matrix.release }}/Containerfile
          platforms: linux/amd64,linux/arm64
          push: true
          no-cache: true
          tags: quay.io/toolbx/debian-toolbox:${{ matrix.release }}

      - name: Push latest tag
        if: env.latest_release == matrix.release
        uses: docker/build-push-action@v3
        with:
          context: images/debian/${{ matrix.release }}
          file: images/debian/${{ matrix.release }}/Containerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: quay.io/toolbx/debian-toolbox:latest
